version: "3"
services:
  web:
    build:
      context: vue-cli
      dockerfile: Dockerfile
    container_name: vue-cli-docker
    command: npm run dev
    volumes:
      - ./app:/code
    ports:
      - "8080:8080"
